name: Test OSVVM

on: workflow_dispatch
 
jobs:
  test-osvvm:
    name: Test OSVVM
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            base-devel
            git            
            mingw-w64-x86_64-tcllib
      - name: Download MSYS2 mingw64 package
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-test.yml
          workflow_conclusion: success
          branch: master
          name: MSYS2 mingw64 package
          skip_unpack: false
          if_no_artifact_found: fail    
      - name: Install NVC
        run: |
          pacman -U --noconfirm *.zst
      - name: Test OSVVM
        run: |
          mkdir tmp && cd tmp
          tclsh ../contrib/osvvm/test-osvvm.tcl
          unzip ../contrib/osvvm/verified_results.zip
          diff -r results/ verified_results/
